### PR TITLE
feat(dynamic): Add raytracing for aperture groups

### PR DESCRIPTION
**Pull request by mikkelkp**

### CODE REVIEW

**Review by chriswmackey — COMMENTED** [review]
Hey @mikkelkp . This generally looks good but I feel that I should test it locally and make sure that I fully understand it before giving the thumbs up (see basecamp for some challenges that I'm having here). My only other comment is that we should probably delete the old `_raytracing.py` module if it is no longer being used.

**Review by chriswmackey — CHANGES_REQUESTED** [review]
Hey @mikkelkp ,
I was just wondering if there was any reason why the old `_raytracing.py` module was still included in this PR.

I have tested it and it generally looks good apart from two things:
1. I think we should remove the `annual_daylight_results` alias on the results output of the recipe, given that the structure of this result folder has changed so much and the old handlers won't deal with it as nicely.
2. The unused `_raytracing.py` module mentioned above.

Once we address these two things, I think we can merge.

**Comment by mikkelkp** [comment]
Hi @chriswmackey,

1. I have removed the alias.
2. Do you mean `pollination/annual_daylight/two_phase/_raytracing.py`? If so it is used. If you refer to something else I am not sure I follow.

**Review by chriswmackey — APPROVED** [review]
Thanks, @mikkelkp ,

Sorry for the confusion with number 2. I think I just misread the git changes as git seems to understand that the original file just changed locations.

Feel free to merge whenever you are ready.

**Pull request merged**
